/* ky2072 KeYang 2022-05-17*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ky2072_fre_entity_PathDepOptionPricer */
#include "price_one_option.cuh"

#ifndef _Included_com_ky2072_fre_entity_PathDepOptionPricer
#define _Included_com_ky2072_fre_entity_PathDepOptionPricer
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_ky2072_fre_entity_PathDepOptionPricer
	 * Method:    priceByGPU
	 * Signature: (IDIDDDIDDI)D
	 */
	JNIEXPORT jdouble JNICALL Java_com_ky2072_fre_entity_PathDepOptionPricer_priceByGPU
	(JNIEnv*, jobject, jint, jdouble, jint, jdouble, jdouble, jdouble, jint, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif